services:
  backend:
    build: .
    image: ptsdetect-api
    environment:
      ASPNETCORE_URLS: "http://+:5000"
      MongoDbOptions__ConnectionString: "mongodb://root:9BjFZXmE2d@mongo"
      MongoDbOptions__AppDatabaseName: "AppDB"
      JwtOptions__Issuer: "http://localhost:5000"
      JwtOptions__Audience: "http://localhost:5173"
      FrontendOptions__BaseUrl: "http://localhost:5173"
      AzureStorageOptions__ConnectionString: ${AzureStorageOptions__ConnectionString}
      SendGridOptions__ApiKey: ${SendGridOptions__ApiKey}
      SendGridOptions__VerifyEmailTemplateId: ${SendGridOptions__VerifyEmailTemplateId}
      SendGridOptions__ResetPasswordTemplateId: ${SendGridOptions__ResetPasswordTemplateId}
      EmailOptions__ServiceEmail: ${EmailOptions__ServiceEmail}
      CorsOptions__AllowedOrigins__0: "http://localhost:5173"
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:5000/healthz || exit
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  mongo:
    image: mongo:7.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 9BjFZXmE2d
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
