pr:
  branches:
    include:
      - main
  paths:
    include:
      - backend/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    displayName: 'Checkout repository'

  - script: dotnet restore
    displayName: 'Restore NuGet packages'
  
  - script: dotnet build --configuration Release
    displayName: 'Build PTSDetect API'